version: '2'
services:
  ganache:
    image: trufflesuite/ganache-cli:v6.4.3
    container_name: ganache

  wildcards:
    build: .
    container_name: wildcards
    environment:
      - BLOCKCHAIN_NODE_HOST=ganache
